server:
  port: 8050
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
zuul:
  ignoredServices: '*'
  routes:
    user-app:
      path: /user/**
      serviceId: provider-user
    sidecar-app:
      path: /car/**
      serviceId: sidecar